---

- name: Deploy Docker Image into Application server
  hosts: astro
  remote_user: ubuntu
  vars:
    AWS_REGION: 'ap-south-1'
    ECR_REPOS: 829173323501.dkr.ecr.ap-south-1.amazonaws.com/sciflare-website
    BUILD_NUMBER: '{{BUILD_NUMBER}}'
    CONTAINER_NAME: AstroWebapps
  tasks:
    - name: Login into ECR repos
      shell: |
        aws ecr get-login-password --region {{AWS_REGION}} | docker login --username AWS --password-stdin {{ECR_REPOS}}
      failed_when: "'Login Succeeded'not in login_result.stdout"
    - name: Pull Docker Images For AstroWebapps Module
      shell: |
        docker pull {{ECR_REPOS}}/{{BUILD_NUMBER}}
    - name: Run Docker Containers Astrowebapp Module
      shell: |
        docker run -d --name {{CONTAINER_NAME}} \
          -p 8080:8080 {{ECR_REPOS}}/{{BUILD_NUMBER}}